---

dependency:
  name: galaxy
  optiones:
    role-file: requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint

platforms: 
  - name: instance-1
    config_options:
      synced_folder: false
    box: centos/7
    memory: 256
    cpus: 1
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - keepalived
  - name: instance-2
    config_options:
      synced_folder: false
    box: centos/7
    memory: 256
    cpus: 1
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - keepalived  
  - name: instance-3
    config_options:
      synced_folder: false
    box: centos/7
    memory: 256
    cpus: 1
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - keepalived

provisioner:
  name: ansible
  options:
    become: true
  log: true
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
