---

- name: Install packages
  yum:
    name: "{{ keepalived_packages }}"
    state: latest
    update_cache: true

- name: Create keepalived configuration file
  template:
    src: keepalived.j2
    dest: "{{ keepalived_config_file }}"
  notify: keepalived_restart

- name: Enable keepalived service
  service:
    name: keepalived
    enabled: true
